django-lectures/django-four/learning_templates/basic_app/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url

# For templace tagging
app_name = 'basic_app'

urlpatterns = [
    path('',views.index, name='index'),
    path('index',views.index, name='index'),
    path('relative',views.relative,name='relative'),
    path('other',views.other,name='other'),
    path('base',views.base,name='base'),
]

django-lectures/django-four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from basic_app import views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),
    path('basic_app/',include('basic_app.urls')),
]

django-lectures/django-four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

django-lectures/django-four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text': 'This is a django learning session', 'number': 100}
    return render(request, 'basic_app/index.html',context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/rel_url_templates.html')

def base(request):
    return render(request, 'basic_app/base.html')

django-lectures/django-four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="/basic_app/">DellEMC</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:index'%}">Index</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other'%}">Other</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:relative'%}">RelativeURL</a></li>
        </ul>
      </div>
    </nav>
    <!-- Body Container -->
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

django-lectures/django-four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to Index</h1>
    <pre>{{ text|cut:'learning' }}:{{ number|add:"10" }}</pre>
{% endblock %}

django-lectures/django-four/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to Other Page</h1>
    <h2>This is an example of template inheritance - DRY Method</h2>
{% endblock %}

django-lectures/django-four/learning_templates/templates/basic_app/rel_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to RelativeURL Page</h1>
{% endblock %}